#!/usr/bin/env node
/**
 * Scans public/assets/ for files matching the slot ids in src/assets/slots.json
 * and writes src/assets/available.generated.ts, which the film reads to decide
 * whether to show a real asset or its procedural fallback.
 *
 * Runs automatically before `npm run studio` / `npm run render*`.
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const {slots} = JSON.parse(fs.readFileSync(path.join(root, 'src/assets/slots.json'), 'utf8'));
const assetsDir = path.join(root, 'public/assets');
const files = fs.existsSync(assetsDir) ? fs.readdirSync(assetsDir) : [];

const VIDEO = new Set(['mp4', 'webm', 'mov']);
const AUDIO = new Set(['mp3', 'wav', 'm4a', 'aac', 'ogg']);

const available = {};
for (const slot of slots) {
  // First matching extension in the slot's preference order wins.
  for (const ext of slot.kinds) {
    const match = files.find((f) => f.toLowerCase() === `${slot.id}.${ext}`);
    if (match) {
      available[slot.id] = {
        file: `assets/${match}`,
        kind: VIDEO.has(ext) ? 'video' : AUDIO.has(ext) ? 'audio' : 'image',
      };
      break;
    }
  }
}

const generatedAudio = {
  music: fs.existsSync(path.join(root, 'public/audio/generated/music.wav')),
  sfx: fs.existsSync(path.join(root, 'public/audio/generated/sfx.wav')),
};

const unknown = files.filter(
  (f) => !f.startsWith('.') && f !== 'README.md' && !Object.values(available).some((a) => a.file === `assets/${f}`),
);

const out = `// AUTO-GENERATED by scripts/scan-assets.mjs. Do not edit by hand.
// Re-run \`npm run assets:scan\` after adding or removing files in public/assets/.
export type AvailableAsset = {file: string; kind: 'image' | 'video' | 'audio'};

export const AVAILABLE_ASSETS: Record<string, AvailableAsset> = ${JSON.stringify(available, null, 2)};

export const GENERATED_AUDIO = ${JSON.stringify(generatedAudio, null, 2)};
`;
fs.writeFileSync(path.join(root, 'src/assets/available.generated.ts'), out);

const ids = Object.keys(available);
console.log(`[assets] ${ids.length}/${slots.length} slots filled${ids.length ? `: ${ids.join(', ')}` : ''}`);
if (unknown.length) {
  console.warn(`[assets] ignored (name does not match a slot id): ${unknown.join(', ')}`);
}
