// AUTO-GENERATED by scripts/scan-assets.mjs. Do not edit by hand.
// Re-run `npm run assets:scan` after adding or removing files in public/assets/.
export type AvailableAsset = {file: string; kind: 'image' | 'video' | 'audio'};

export const AVAILABLE_ASSETS: Record<string, AvailableAsset> = {};

export const GENERATED_AUDIO = {
  "music": true,
  "sfx": true
};
